### ISSUE TITLE
Search is void

### ISSUE THREAD

**Issue by rogorido** [jorenvo/simple-mpc#4]
Thanks a lot for the package. This is a very good idea to take mu4e as an inspiration.

I have following problem: if I write in the console
mpc search composer Bach
I get a lot of results. 

But the same search inside simple-mpc does not return results. Any ideas?

**Comment by jorenvo** [comment]
Indeed, this seems to be a bug introduced by 89440b017d74fd675f22e0505ba8d86eabf0bc5a. It occurs when `simple-mpc-playlist-format` is not set, which is why I have not noticed it. A quick workaround would be to set the following in your Emacs configuration:

```
(setq simple-mpc-playlist-format "%file%")
```

Alternatively you could use `M-x customize-group <RET> simple-mpc <RET>` and configure the value there. I will write a patch that resolves this bug properly.

**Comment by jorenvo** [comment]
The issue has been solved in c920da63cc2c5cbc56fb8eb87f260dfffba163f9. If you installed through MELPA then you should be able to update the package in a couple of hours. It currently takes around 4 hours for MELPA to update all the packages.

Thank you for the report. If you run into more issues then don't hesitate to report them.

**Comment by rogorido** [comment]
Yes, indeed. This is now working. Thanks a lot again for the package!

**Comment by jorenvo** [comment]
No problem, thanks for bringing the problem to my attention.
